"""Userscript storage: JS helpers that auto-run at document_start via extension.

Userscripts are stored on disk under ``<DATA_DIR>/userscripts/<name>/script.js``.
A Chrome extension is generated at ``<DATA_DIR>/userscripts-extension/`` with a
``content.js`` that inlines all installed userscripts (each wrapped in
try/catch), plus a set of built-in default userscripts shipped with odda.
The extension is loaded via CDP ``Extensions.loadUnpacked`` and runs at
``document_start`` in the ``MAIN`` world, so ``window`` modifications are
visible to the page and to ``odda eval``.
"""

from __future__ import annotations

import shutil
from importlib import resources
from typing import TYPE_CHECKING, Any

from odda import flowstore

if TYPE_CHECKING:
    from pathlib import Path

USERSCRIPTS_DIR_NAME = "userscripts"
USERSCRIPTS_EXTENSION_DIR_NAME = "userscripts-extension"
SCRIPT_FILENAME = "script.js"
DEFAULT_USERSCRIPTS_PACKAGE = "odda.userscripts.default"

MANIFEST_JSON = """{
  "manifest_version": 3,
  "name": "odda-userscripts",
  "version": "1.0",
  "content_scripts": [{
    "matches": ["<all_urls>"],
    "js": ["content.js"],
    "run_at": "document_start",
    "world": "MAIN",
    "all_frames": true
  }]
}
"""


def install(name: str, source: str) -> dict[str, Any]:
    """Install a userscript, overwriting any existing one, and resync the extension."""
    script_dir = flowstore.DATA_DIR / USERSCRIPTS_DIR_NAME / name
    if script_dir.exists():
        shutil.rmtree(script_dir)
    script_dir.mkdir(parents=True, exist_ok=True)
    (script_dir / SCRIPT_FILENAME).write_text(source, encoding="utf-8")
    sync_extension()
    return {"name": name, "size": len(source)}


def remove(name: str) -> dict[str, Any]:
    """Remove a userscript and resync the extension.

    Raises:
        ValueError: If the script does not exist.
    """
    script_dir = flowstore.DATA_DIR / USERSCRIPTS_DIR_NAME / name
    if not script_dir.exists():
        msg = f"Userscript '{name}' not found"
        raise ValueError(msg)
    shutil.rmtree(script_dir)
    sync_extension()
    return {"name": name, "removed": True}


def list_scripts() -> list[dict[str, Any]]:
    """List all installed userscripts from disk."""
    d = flowstore.DATA_DIR / USERSCRIPTS_DIR_NAME
    if not d.exists():
        return []
    scripts: list[dict[str, Any]] = []
    for entry in sorted(d.iterdir()):
        if not entry.is_dir():
            continue
        script_file = entry / SCRIPT_FILENAME
        if script_file.exists():
            scripts.append({"name": entry.name, "size": script_file.stat().st_size})
    return scripts


def _read_default_scripts() -> list[tuple[str, str]]:
    """Load built-in default userscripts packaged with odda.

    Returns:
        A list of (name, source) tuples for each ``*.js`` file in the
        ``odda.userscripts.default`` package.
    """
    return [
        (entry.name, entry.read_text(encoding="utf-8"))
        for entry in sorted(resources.files(DEFAULT_USERSCRIPTS_PACKAGE).iterdir())
        if entry.is_file() and entry.name.endswith(".js")
    ]


def sync_extension() -> Path:
    """Regenerate the extension's content.js from installed and default userscripts.

    Default userscripts are inlined first so they establish globals before any
    user-installed script runs. Each script is wrapped in try/catch so one
    failing script doesn't break the rest. Writes manifest.json if missing.
    Returns the extension dir path.
    """
    ext_dir = flowstore.DATA_DIR / USERSCRIPTS_EXTENSION_DIR_NAME
    ext_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = ext_dir / "manifest.json"
    if not manifest_path.exists():
        manifest_path.write_text(MANIFEST_JSON, encoding="utf-8")

    parts: list[str] = ["// Auto-generated by odda. Do not edit.\n"]

    for name, source in _read_default_scripts():
        parts.append(
            f"// === default userscript: {name} ===\n"
            f"try {{\n{source}\n}} catch (e) {{\n"
            f"  console.error('[odda] default userscript {name} failed:', e);\n"
            f"}}\n"
        )

    scripts_dir = flowstore.DATA_DIR / USERSCRIPTS_DIR_NAME
    if scripts_dir.exists():
        for entry in sorted(scripts_dir.iterdir()):
            if not entry.is_dir():
                continue
            script_file = entry / SCRIPT_FILENAME
            if not script_file.exists():
                continue
            source = script_file.read_text(encoding="utf-8")
            parts.append(
                f"// === userscript: {entry.name} ===\n"
                f"try {{\n{source}\n}} catch (e) {{\n"
                f"  console.error('[odda] userscript {entry.name} failed:', e);\n"
                f"}}\n"
            )
    (ext_dir / "content.js").write_text("\n".join(parts), encoding="utf-8")
    return ext_dir
